development: &defaults
  adapter: postgresql
  database: laeron_development
  user: postgres
  password: vagrant
  host: localhost

test:
  <<: *defaults
  database: laeron_test

production:
  <<: *defaults
  database: laeron
